# Generated by Django 4.2.17 on 2025-01-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='plano',
            field=models.CharField(choices=[('basico', 'Básico - 100Mbps'), ('intermediario', 'Intermediário - 300Mbps'), ('avancado', 'Avançado - 1Gbps')], max_length=50),
        ),
    ]
