# Generated by Django 4.2.17 on 2025-01-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plano'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plano',
            new_name='Servico',
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicos', models.ManyToManyField(related_name='combos', to='core.servico')),
            ],
        ),
    ]
