# Generated by Django 4.2.17 on 2025-01-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_plano_servico_combo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Combo',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
