# Generated by Django 4.2.17 on 2025-01-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_combo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='nome',
        ),
    ]
