# Generated by Django 4.2.17 on 2025-01-07 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_combo_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('data_assinatura', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Combo',
        ),
        migrations.RenameField(
            model_name='assinatura',
            old_name='data_assinatura',
            new_name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='assinatura',
            name='email',
        ),
        migrations.RemoveField(
            model_name='assinatura',
            name='plano',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='descricao1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='descricao10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='descricao2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='descricao3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='descricao4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='descricao5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='descricao6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='descricao7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='descricao8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='descricao9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='link1',
            field=models.CharField(choices=[('wifi_turbo', 'Wi-Fi Turbo'), ('telemedicina', 'Telemedicina'), ('planos_internet', 'Planos de Internet'), ('tv_assinatura', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('controle', 'Plano Controle'), ('nenhum', 'Nenhum Link')], default='nenhum', max_length=50),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='link10',
            field=models.CharField(choices=[('wifi_turbo', 'Wi-Fi Turbo'), ('telemedicina', 'Telemedicina'), ('planos_internet', 'Planos de Internet'), ('tv_assinatura', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('controle', 'Plano Controle'), ('nenhum', 'Nenhum Link')], default='nenhum', max_length=50),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='link2',
            field=models.CharField(choices=[('wifi_turbo', 'Wi-Fi Turbo'), ('telemedicina', 'Telemedicina'), ('planos_internet', 'Planos de Internet'), ('tv_assinatura', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('controle', 'Plano Controle'), ('nenhum', 'Nenhum Link')], default='nenhum', max_length=50),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='link3',
            field=models.CharField(choices=[('wifi_turbo', 'Wi-Fi Turbo'), ('telemedicina', 'Telemedicina'), ('planos_internet', 'Planos de Internet'), ('tv_assinatura', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('controle', 'Plano Controle'), ('nenhum', 'Nenhum Link')], default='nenhum', max_length=50),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='link4',
            field=models.CharField(choices=[('wifi_turbo', 'Wi-Fi Turbo'), ('telemedicina', 'Telemedicina'), ('planos_internet', 'Planos de Internet'), ('tv_assinatura', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('controle', 'Plano Controle'), ('nenhum', 'Nenhum Link')], default='nenhum', max_length=50),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='link5',
            field=models.CharField(choices=[('wifi_turbo', 'Wi-Fi Turbo'), ('telemedicina', 'Telemedicina'), ('planos_internet', 'Planos de Internet'), ('tv_assinatura', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('controle', 'Plano Controle'), ('nenhum', 'Nenhum Link')], default='nenhum', max_length=50),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='link6',
            field=models.CharField(choices=[('wifi_turbo', 'Wi-Fi Turbo'), ('telemedicina', 'Telemedicina'), ('planos_internet', 'Planos de Internet'), ('tv_assinatura', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('controle', 'Plano Controle'), ('nenhum', 'Nenhum Link')], default='nenhum', max_length=50),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='link7',
            field=models.CharField(choices=[('wifi_turbo', 'Wi-Fi Turbo'), ('telemedicina', 'Telemedicina'), ('planos_internet', 'Planos de Internet'), ('tv_assinatura', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('controle', 'Plano Controle'), ('nenhum', 'Nenhum Link')], default='nenhum', max_length=50),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='link8',
            field=models.CharField(choices=[('wifi_turbo', 'Wi-Fi Turbo'), ('telemedicina', 'Telemedicina'), ('planos_internet', 'Planos de Internet'), ('tv_assinatura', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('controle', 'Plano Controle'), ('nenhum', 'Nenhum Link')], default='nenhum', max_length=50),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='link9',
            field=models.CharField(choices=[('wifi_turbo', 'Wi-Fi Turbo'), ('telemedicina', 'Telemedicina'), ('planos_internet', 'Planos de Internet'), ('tv_assinatura', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('controle', 'Plano Controle'), ('nenhum', 'Nenhum Link')], default='nenhum', max_length=50),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='ordem',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='tipo',
            field=models.CharField(choices=[('combos', 'Combos'), ('internet', 'Planos de Internet'), ('tv', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('controle', 'Plano Controle'), ('movel', 'Internet Móvel'), ('telemedicina', 'Telemedicina'), ('upgrades', 'Upgrades')], default='combos', max_length=50),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assinaturacliente',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='core.assinatura'),
        ),
    ]
