# Generated by Django 4.2.17 on 2025-01-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_assinatura_descricao1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
