# Generated by Django 4.2.17 on 2025-01-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_assinatura_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('internet', 'Internet'), ('tv', 'TV'), ('telefonia', 'Telefonia'), ('chip_movel', 'Chip Móvel'), ('telemedicina', 'Telemedicina'), ('ponto_wifi', 'Ponto Wi-Fi 2.4G'), ('ip_gamer', 'IP Gamer')], max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
