# Generated by Django 4.2.17 on 2025-01-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_servico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['categoria', 'preco'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AddField(
            model_name='servico',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Destaque'),
        ),
        migrations.AddField(
            model_name='servico',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='servicos/', verbose_name='Imagem do Serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='categoria',
            field=models.CharField(choices=[('internet', 'Internet'), ('tv', 'TV'), ('telefonia', 'Telefonia'), ('chip_movel', 'Chip Móvel'), ('telemedicina', 'Telemedicina'), ('ponto_wifi', 'Ponto Wi-Fi 2.4G'), ('ip_gamer', 'IP Gamer')], max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço (R$)'),
        ),
    ]
