# Generated by Django 4.2.17 on 2025-01-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_servico_options_servico_destaque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaLimite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('internet', 'Internet'), ('tv', 'TV'), ('telefonia', 'Telefonia'), ('chip_movel', 'Chip Móvel'), ('telemedicina', 'Telemedicina'), ('ponto_wifi', 'Ponto Wi-Fi 2.4G'), ('ip_gamer', 'IP Gamer')], max_length=50, unique=True)),
                ('limite', models.PositiveIntegerField(default=1, help_text='Quantos serviços desta categoria podem ser selecionados em um combo.')),
            ],
        ),
    ]
