# Generated by Django 4.2.17 on 2025-01-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_servico_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_modal', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='link1',
            field=models.CharField(choices=[('wifi_turbo', 'Wi-Fi Turbo'), ('telemedicina', 'Telemedicina'), ('planos_internet', 'Planos de Internet'), ('tv_assinatura', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('sva_escolha', 'SVA da Sua Escolha'), ('controle', 'Plano Controle'), ('linha_telefonica', 'Linha Telefônica'), ('atendimento_online', 'Atendimento 24h Online'), ('fibra_exclusivo', 'Exclusivo para Clientes Fibra'), ('nenhum', 'Nenhum Link')], default='nenhum', max_length=50),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='link10',
            field=models.CharField(choices=[('wifi_turbo', 'Wi-Fi Turbo'), ('telemedicina', 'Telemedicina'), ('planos_internet', 'Planos de Internet'), ('tv_assinatura', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('sva_escolha', 'SVA da Sua Escolha'), ('controle', 'Plano Controle'), ('linha_telefonica', 'Linha Telefônica'), ('atendimento_online', 'Atendimento 24h Online'), ('fibra_exclusivo', 'Exclusivo para Clientes Fibra'), ('nenhum', 'Nenhum Link')], default='nenhum', max_length=50),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='link2',
            field=models.CharField(choices=[('wifi_turbo', 'Wi-Fi Turbo'), ('telemedicina', 'Telemedicina'), ('planos_internet', 'Planos de Internet'), ('tv_assinatura', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('sva_escolha', 'SVA da Sua Escolha'), ('controle', 'Plano Controle'), ('linha_telefonica', 'Linha Telefônica'), ('atendimento_online', 'Atendimento 24h Online'), ('fibra_exclusivo', 'Exclusivo para Clientes Fibra'), ('nenhum', 'Nenhum Link')], default='nenhum', max_length=50),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='link3',
            field=models.CharField(choices=[('wifi_turbo', 'Wi-Fi Turbo'), ('telemedicina', 'Telemedicina'), ('planos_internet', 'Planos de Internet'), ('tv_assinatura', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('sva_escolha', 'SVA da Sua Escolha'), ('controle', 'Plano Controle'), ('linha_telefonica', 'Linha Telefônica'), ('atendimento_online', 'Atendimento 24h Online'), ('fibra_exclusivo', 'Exclusivo para Clientes Fibra'), ('nenhum', 'Nenhum Link')], default='nenhum', max_length=50),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='link4',
            field=models.CharField(choices=[('wifi_turbo', 'Wi-Fi Turbo'), ('telemedicina', 'Telemedicina'), ('planos_internet', 'Planos de Internet'), ('tv_assinatura', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('sva_escolha', 'SVA da Sua Escolha'), ('controle', 'Plano Controle'), ('linha_telefonica', 'Linha Telefônica'), ('atendimento_online', 'Atendimento 24h Online'), ('fibra_exclusivo', 'Exclusivo para Clientes Fibra'), ('nenhum', 'Nenhum Link')], default='nenhum', max_length=50),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='link5',
            field=models.CharField(choices=[('wifi_turbo', 'Wi-Fi Turbo'), ('telemedicina', 'Telemedicina'), ('planos_internet', 'Planos de Internet'), ('tv_assinatura', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('sva_escolha', 'SVA da Sua Escolha'), ('controle', 'Plano Controle'), ('linha_telefonica', 'Linha Telefônica'), ('atendimento_online', 'Atendimento 24h Online'), ('fibra_exclusivo', 'Exclusivo para Clientes Fibra'), ('nenhum', 'Nenhum Link')], default='nenhum', max_length=50),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='link6',
            field=models.CharField(choices=[('wifi_turbo', 'Wi-Fi Turbo'), ('telemedicina', 'Telemedicina'), ('planos_internet', 'Planos de Internet'), ('tv_assinatura', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('sva_escolha', 'SVA da Sua Escolha'), ('controle', 'Plano Controle'), ('linha_telefonica', 'Linha Telefônica'), ('atendimento_online', 'Atendimento 24h Online'), ('fibra_exclusivo', 'Exclusivo para Clientes Fibra'), ('nenhum', 'Nenhum Link')], default='nenhum', max_length=50),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='link7',
            field=models.CharField(choices=[('wifi_turbo', 'Wi-Fi Turbo'), ('telemedicina', 'Telemedicina'), ('planos_internet', 'Planos de Internet'), ('tv_assinatura', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('sva_escolha', 'SVA da Sua Escolha'), ('controle', 'Plano Controle'), ('linha_telefonica', 'Linha Telefônica'), ('atendimento_online', 'Atendimento 24h Online'), ('fibra_exclusivo', 'Exclusivo para Clientes Fibra'), ('nenhum', 'Nenhum Link')], default='nenhum', max_length=50),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='link8',
            field=models.CharField(choices=[('wifi_turbo', 'Wi-Fi Turbo'), ('telemedicina', 'Telemedicina'), ('planos_internet', 'Planos de Internet'), ('tv_assinatura', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('sva_escolha', 'SVA da Sua Escolha'), ('controle', 'Plano Controle'), ('linha_telefonica', 'Linha Telefônica'), ('atendimento_online', 'Atendimento 24h Online'), ('fibra_exclusivo', 'Exclusivo para Clientes Fibra'), ('nenhum', 'Nenhum Link')], default='nenhum', max_length=50),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='link9',
            field=models.CharField(choices=[('wifi_turbo', 'Wi-Fi Turbo'), ('telemedicina', 'Telemedicina'), ('planos_internet', 'Planos de Internet'), ('tv_assinatura', 'TV por Assinatura'), ('streaming', 'Pacote de Streamings'), ('sva_escolha', 'SVA da Sua Escolha'), ('controle', 'Plano Controle'), ('linha_telefonica', 'Linha Telefônica'), ('atendimento_online', 'Atendimento 24h Online'), ('fibra_exclusivo', 'Exclusivo para Clientes Fibra'), ('nenhum', 'Nenhum Link')], default='nenhum', max_length=50),
        ),
    ]
